src/app/recycle/components/DetectObject.tsx
src/app/recycle/components/DetectedItems.tsx
src/app/recycle/containers/DetectContainer.tsx
src/app/recycle/detect/page.tsx
src/app/recycle/libs.ts
src/app/recycle/services/actions.tsx

recycle 페이지 코드

---

src/app/member/_containers/LoginContainer.tsx

LoginContainer 오류수정
---
---
---

LoginContainer 오류수정

---

package.json
src/app/page.tsx
src/app/recycle/_services/actions.ts
src/app/recycle/containers/RecycleContainer.tsx
src/app/recycle/page.tsx
yarn.lock

- RecycleContainer(클라)에서 react-cookie(useCookies)로 guestCount 증가/차단 처리
- UserContext 기반으로 로그인 시 /recycle/detect 로 즉시 라우팅
- processRecycle(서버): guestId(httpOnly) 발급, guestCount는 읽기만 하여 최종 redirect
- /recycle 트리에 CookiesProvider 적용 (useCookies 컨텍스트 보장)
- 주석 보강: parseInt NaN 보정, sameSite=lax 설명
---
---
---

CSR 게이트(guestCount) 도입 및 회원 즉시 이동, 서버 최종 검증 추가

---

src/app/recycle/containers/DetectContainer.tsx

분리수거 감지 페이지 -> 결과 페이지 이동 구현
---
---
---

분리수거 감지 페이지 -> 결과 페이지 이동 구현

---

src/app/recycle/components/ResultList.tsx
src/app/recycle/containers/ResultContainer.tsx

결과 페이지 이미지 조회 성공

---

src/app/member/_components/JoinForm.tsx

회원가입 폼 문제 해결

---

src/app/_global/components/Pagination.tsx
src/app/event/_components/EventList.tsx
yarn.lock

페이징 공통으로 분리

---

src/app/_global/components/Pagination.tsx
src/app/event/_components/EventList.tsx

페이지네이션 css추가

---

src/app/mypage/_components/RecycleList.tsx
src/app/mypage/_containers/RecycleContainer.tsx

분리수거 이미지 저장 페이지 구현
---
---
---

mypagerecycle

---

src/app/recycle/components/RecycleGuide.tsx
src/app/recycle/components/ResultList.tsx
src/app/recycle/containers/ResultContainer.tsx

페이지네이션 기준 변경

---

src/app/recycle/components/RecycleGuide.tsx
src/app/recycle/components/ResultList.tsx
src/app/recycle/containers/ResultContainer.tsx

분리배출 표시방법 변경

---

src/app/recycle/_services/actions.ts
src/app/recycle/containers/ResultContainer.tsx

분리수거 쪽 페이지 이동 버그 수정

---

src/app/_global/components/Pagination.tsx
src/app/admin/crawler/_containers/CrawlerContainer.tsx
src/app/event/[hash]/page.tsx
src/app/event/_components/EventList.tsx
src/app/event/_containers/EventListContainer.tsx
src/app/event/_services/actions.ts
src/app/event/page.tsx

환경행사 페이지네이션, 검색 수정
---
---
---

환경행사 페이지네이션, 검색 수정

---

src/app/mypage/_containers/ProfileContainer.tsx

마이페이지 개인정보 비밀번호 인증 기능 보완
---
---
---

마이페이지 개인정보 비번인증기능 보완

---

src/app/member/_components/LoginForm.tsx
src/app/member/_containers/JoinContainer.tsx
src/app/member/find-password/FindPasswordForm.tsx

오류 수정 및 백엔드 전달 값 재설정
---
---
---

오류 수정 및 백엔드 전달 값 재설정

---

src/app/member/withdraw/WithdrawContainer.tsx
src/app/mypage/_components/ProfileForm.tsx
src/app/mypage/_containers/ProfileContainer.tsx

프로필 수정 기능 버그 수정

---

src/app/_global/outlines/Footer.tsx
src/app/_global/outlines/Header.tsx
src/app/member/login/page.tsx
src/app/member/social/[channel]/callback/route.ts
src/app/recycle/components/DetectedItems.tsx
src/app/recycle/containers/DetectContainer.tsx
src/app/recycle/detect/page.tsx

소셜 로그인 오류 수정 및 스타일 작업
---
---
---

소셜 로그인 오류 수정 및 스타일 작업

---

package.json
src/app/_global/components/LayerPopup.tsx
src/app/main/containers/MainContainer.tsx
src/app/member/withdraw/WithdrawContainer.tsx

MainContainer에서 발생하는 오류를 해결했습니다.
---
---
---

MainContainer 오류 해결

---

src/app/_global/hooks/useMenu.tsx
src/app/_global/outlines/Header.tsx
src/app/_global/outlines/admin/Side.tsx
src/app/_global/outlines/admin/SubMenu.tsx
src/app/_global/values/menus.ts
src/app/admin/board/_components/BoardItems.tsx
src/app/admin/board/_components/BoardSearchForm.tsx
src/app/admin/board/_containers/ListContainer.tsx
src/app/main/containers/MainContainer.tsx
src/app/recycle/containers/ResultContainer.tsx

게시판 관리자 스타일 작업

---

src/app/member/withdraw/_components/WithdrawComponent.tsx
src/app/member/withdraw/containers/WithdrawContainer.tsx
src/app/member/withdraw/page.tsx
tsconfig.json

회원탈퇴 페이지 스타일

---

src/app/member/_components/JoinForm.tsx
src/app/recycle/result/page.tsx

비밀번호 강도 스타일 변경

---

src/app/member/_components/JoinForm.tsx

비밀번호 강도에 따른 메세지
